#!/bin/bash
# configure-wifi
#
# Copyright 2018, F123 Consulting, <information@f123.org>
# Copyright 2018, Kyle, <kyle@free2.ml>
# Copyright 2018, Storm Dragon, <storm_dragon@linux-a11y.org>
#
# This is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3, or (at your option) any later
# version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this package; see the file COPYING.  If not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
#--code--

# Some useful settings and functions needed in this configurator

# Get the coluns and lines of the "screen"
cols=$(tput cols)
lines=$(tput lines)
# Settings to improve accessibility of dialog.
export DIALOGOPTS='--insecure --no-lines --visit-items'

passwordbox() {
    # Returns: text entered by the user
    # Args 1, Instructions for box.
    # args: 2 initial text (optional)
    dialog --backtitle "$(gettext "Enter text and press enter. Press escape to cancel.")" \
        --passwordbox "$(gettext "$1")" $((lines - 4)) $cols "$2" --stdout
}

msgbox() {
# Returns: None
# Shows the provided message on the screen with an ok button.
dialog --msgbox "$(gettext "$*")" $lines $cols
}

infobox() {
# Returns: None
# Shows the provided message on the screen with no buttons.
dialog --infobox "$(gettext "$*")" $lines $cols
}

menulist() {
    # Args: minimum group 2, multiples of 2, "tag" "choice"
    # returns: selected tag
      local menuList
    if [[ $((${#@} / 2)) -gt $((lines - 5)) ]]; then
        local optionSize=$((lines - 5))
    else
        local optionSize=$((${#@} / 2))
    fi
    ifs="$IFS"
    IFS=$'\n'
    dialog --backtitle "$(gettext "Use the up and down arrow keys to find the option you want, then press enter to select it. Press escape to cancel.")" \
        --menu "$(gettext "Please select your wireless network")" $((lines - 4)) $cols $optionSize $@ --stdout
    IFS="$ifs"
}

# Be sure the wireless interface is up.
ip link set up dev wlan0

# Scan for available wifi networks and store them in an array.
infobox "Scanning for available wireless networks ..."
ifs=$IFS
IFS=$'\n'
for ESSID in $(iwlist wlan0 scan | grep ESSID | cut -d\" -f2); do
	networks+=("$ESSID")
	networks+=(" ")
done
IFS=$ifs

# Present the available networks in a selectable menu
	network="$(menulist "${networks[@]}")"
test -z $network && exit 0

pass="$(passwordbox "Enter the password for ${network}. Just press the enter key if $network is unsecured.")" || exit 0
infobox "Connecting to ${network}..."

# Create the systemd network file if it doesn't already exist
mkdir -p /etc/systemd/network
cat > /etc/systemd/network/wlan0.network <<-endOfFile
	[Match]
	Name=wlan0
		[Network]
	DHCP=yes
endOfFile

# Configure wpa_supplicant
mkdir -p /etc/wpa_supplicant
cat > /etc/wpa_supplicant/wpa_supplicant-wlan0.conf <<-endOfFile
	ctrl_interface=/var/run/wpa_supplicant
	eapol_version=1
	ap_scan=1
	fast_reauth=1

	endOfFile

# Combine the network ESSID and password to add a Network section to the wpa_supplicant configuration file with an encrypted password,
# or if no password is specified, add a Network section with no key management.
if test -z $pass; then
	cat >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf <<-endOfFile
		network={
		    ssid="$network"
		    key_mgmt="NONE"
		}
	endOfFile
else
	wpa_passphrase "$network" "$pass" | grep -v \#psk >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
fi

# Wifi can be a real bear, based on what adapter is being used and driver support.
# In order to try to ensure that any Linux supported wireless adapter will work, we copy wpa_supplicant@.service from /usr/lib/systemd/system into /etc/systemd/system
# and modify it to try nl80211 first, and failing that, to try wext. This should be the default wpa_supplicant@.service in any case, since
# wpa_supplicant@.service and wpa_supplicant-nl80211@.service appear to work, (or not work) in the same way.
cp /usr/lib/systemd/system/wpa_supplicant@.service /etc/systemd/system
sed -i /etc/systemd/system/wpa_supplicant@.service -e 's/-c/-Dnl80211,wext -c/'

# Enable networking and wifi related services
systemctl enable --now systemd-networkd >& /dev/null
systemctl enable --now wpa_supplicant@wlan0 >& /dev/null
systemctl enable --now systemd-resolved >& /dev/null

# Don't make any assumptions. Reload wpa_supplicant service in case wifi is being reconfigured.
systemctl restart wpa_supplicant@wlan0

# Remove any legacy version of resolv.conf and link the version from systemd-resolved
rm -f /etc/resolv.conf
ln -sf /var/run/systemd/resolve/resolv.conf /etc/resolv.conf

# It's a bit hacky, but it seems there's no better way to test connectivity. Within 4 to 8 seconds, if the network is still not connected, there is a problem.
sleep 4
if ping -c 1 google.com >&/dev/null; then
	msgbox "Your wireless network connection has been configured and is now working."
else
	sleep 4
	ping -c 1 google.com && msgbox "Your wireless network connection has been configured and is now working." ||msgbox "There was a problem configuring the wireless network. Be sure you selected the correct network, and that your password is correct."
fi
